### ISSUE TITLE
Incomplete instructions to install io tracer and octf on brand new RHEL 7.6

### ISSUE THREAD

**Issue by jcurryaz1** [Open-CAS/standalone-linux-io-tracer#101]
started with brand new RHEL 7.6 buld (server with gui), system registered with RHEL
download latest GIT for standalone tracer

following the README.md, I ran the setup dependencies.sh for standalone iotracer (log attached), failure

downloaded latest GIT for octf, ran the setup dependencies.sh (log attached)

I am unable to build the tools.

Are there different readmes?
[error-octf.log](https://github.com/Open-CAS/open-cas-telemetry-framework/files/3774103/error-octf.log)
[error-iotrace.log](https://github.com/Open-CAS/open-cas-telemetry-framework/files/3774104/error-iotrace.log)
[error-octf.log](https://github.com/Open-CAS/standalone-linux-io-tracer/files/3774107/error-octf.log)
[error-iotrace.log](https://github.com/Open-CAS/standalone-linux-io-tracer/files/3774108/error-iotrace.log)

**Comment by tomaszrybicki** [comment]
As for standalone-linux-io-tracer:  we have provided a fix in #102 . Please update repository to fix this.

As for OCTF: It seems to be a particular machine's environment problem - proxy address seems to be wrong. Please try to set proxies with 'export http(s)_proxy="address:port"'.
Also please use newest OCTF, as we have recently updated the setup script.

The only READMEs are: 
- standalone-linux-io-tracer [README](https://github.com/Open-CAS/standalone-linux-io-tracer/blob/master/README.md)
- open-cas-telemetry-framework [README](https://github.com/Open-CAS/open-cas-telemetry-framework/blob/master/README.md

For installing iotrace the first one is sufficent.

**Comment by jcurryaz1** [comment]
Tomasz
I did set the proxies using export and it appeared all of the dependencies were installed
I captured the errors from both installs
Regards
Jeff

**Comment by jcurryaz1** [comment]
The instructions are still not working and not clear.
Here is what I tried
1. fresh rhel 7.6 installation, system registered, proxies set
2. pulled octf and standalone zip files
3. In octf folder, ran the ./setup-dependencies .. it completed no errors
4. moved to standalone folder, ran the ./setup-dependencies command
[error.txt](https://github.com/Open-CAS/standalone-linux-io-tracer/files/3780482/error.txt)

Can I get some clean instructions so we can simplify the process?
