### ISSUE TITLE
Support for latest kernel versions

### ISSUE THREAD

**Issue by ApurwaMohite** [Open-CAS/standalone-linux-io-tracer#107]
IOtracer works fine with kernel 3.10. But when 3.10 is upgraded to 5.3.8, it started giving error 'Kernel tracing module is not loaded.'. I tried to re-install it on kernel 5.3.8 but re-installation also fails. I tried to debug the issue, it seems that directory of 3.10 and 5.3.8 are completely different and it is causing IOtracer failure. Is there any plan to support IOtracer on latest kernel versions? Is there any workaround that I can try for now?

**Comment by mariuszbarczak** [comment]
Hi.
Could you attach compilation and installation log?
We'll try to fix that.

**Comment by mariuszbarczak** [comment]
Hi, I got compilation successful on Linux v5.4. Is it working for you?

**Comment by ApurwaMohite** [comment]
Hi,

I am still facing the issue.
System details are :
OS : CentOS Linux release 7.7.1908 (Core)
Kernel version : 5.3.11-1.el7.elrepo.x86_64

I executed following steps:
1. git clone https://github.com/Open-CAS/standalone-linux-io-tracer/
2. cd standalone-linux-io-tracer
3. git checkout $(git tag | grep
"^v[[:digit:]]*.[[:digit:]]*.[[:digit:]]*$" | tail -1)
4. git submodule update --init --recursive
5. ./modules/open-cas-telemetry-framework/setup_dependencies.sh
6. make

Attached compilation logs.

On Mon, Nov 25, 2019 at 5:19 PM Mariusz Barczak <notifications@github.com>
wrote:

> Hi, I got compilation successful on Linux v5.4. Is it working for you?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Open-2DCAS_standalone-2Dlinux-2Dio-2Dtracer_issues_107-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DANJ46EMVUZAZQKDDSPCTC4LQVO3UDA5CNFSM4JNVXSBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFCEA6A-23issuecomment-2D558121080&d=DwMCaQ&c=IGDlg0lD0b-nebmJJ0Kp8A&r=NTSMr_hC-2VBlFrr02tMdlG2ZQ7OSSu8BNkih3kl1q0&m=QfrzSlxro4OaZrnDA3MwMOnxK4YtXwCTa8okyWdiVtM&s=-ATsTL96jLdVacXQ7qDZoj69bnvq9ELLuH2g90pV77A&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANJ46EJV253QQWJDPMYLUYTQVO3UDANCNFSM4JNVXSBA&d=DwMCaQ&c=IGDlg0lD0b-nebmJJ0Kp8A&r=NTSMr_hC-2VBlFrr02tMdlG2ZQ7OSSu8BNkih3kl1q0&m=QfrzSlxro4OaZrnDA3MwMOnxK4YtXwCTa8okyWdiVtM&s=SdaK3elJ0tYcOO_QCBgSJhrXtpkYktTArso4Rm2aY04&e=>
> .
>


-- 
Regards,
Apurwa

mkdir -p build/release
cd build/release && cmake /home/seagate/iotracer/standalone-linux-io-tracer -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/
-- IOTRACE VERSION: 19.6.0
-- IOTRACE LABEL: d5b4396
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- OCTF VERSION: 19.6.0
-- OCTF LABEL: d5b4396
-- Found Protobuf: /usr/lib/libprotobuf.so;-lpthread (found version "3.11.0") 
-- OCTF_CONFIG_FILE set to: /etc/octf/octf.conf
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for limits.h
-- Looking for limits.h - found
-- Found GTest: /usr/lib64/libgtest.so  
-- Found Threads: TRUE  
-- Found Doxygen: /bin/doxygen (found version "1.8.5") found components:  doxygen dot 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/seagate/iotracer/standalone-linux-io-tracer/build/release
make -C build/release all
make[1]: Entering directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
make[2]: Entering directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
make[3]: Entering directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
Scanning dependencies of target safestringlib
make[3]: Leaving directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
make[3]: Entering directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
[  1%] Building C object modules/open-cas-telemetry-framework/source/third_party/CMakeFiles/safestringlib.dir/safestringlib/safeclib/safe_str_constraint.c.o
[  2%] Building C object modules/open-cas-telemetry-framework/source/third_party/CMakeFiles/safestringlib.dir/safestringlib/safeclib/strcpy_s.c.o
[  3%] Building C object modules/open-cas-telemetry-framework/source/third_party/CMakeFiles/safestringlib.dir/safestringlib/safeclib/memcpy_s.c.o
[  4%] Building C object modules/open-cas-telemetry-framework/source/third_party/CMakeFiles/safestringlib.dir/safestringlib/safeclib/memset_s.c.o
[  4%] Building C object modules/open-cas-telemetry-framework/source/third_party/CMakeFiles/safestringlib.dir/safestringlib/safeclib/mem_primitives_lib.c.o
[  5%] Building C object modules/open-cas-telemetry-framework/source/third_party/CMakeFiles/safestringlib.dir/safestringlib/safeclib/abort_handler_s.c.o
[  6%] Building C object modules/open-cas-telemetry-framework/source/third_party/CMakeFiles/safestringlib.dir/safestringlib/safeclib/ignore_handler_s.c.o
[  7%] Building C object modules/open-cas-telemetry-framework/source/third_party/CMakeFiles/safestringlib.dir/safestringlib/safeclib/safe_mem_constraint.c.o
make[3]: Leaving directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
[  7%] Built target safestringlib
make[3]: Entering directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
[  8%] Running cpp protocol buffer compiler on traceDefinitions.proto
[  8%] Running cpp protocol buffer compiler on configuration.proto
configuration.proto:7:1: warning: Import opts.proto is unused.
[  9%] Running cpp protocol buffer compiler on defs.proto
[ 10%] Running cpp protocol buffer compiler on InterfaceCLI.proto
[ 11%] Running cpp protocol buffer compiler on InterfaceIdentification.proto
InterfaceIdentification.proto:8:1: warning: Import opts.proto is unused.
[ 11%] Running cpp protocol buffer compiler on InterfaceTraceParsing.proto
InterfaceTraceParsing.proto:10:1: warning: Import traceDefinitions.proto is unused.
[ 12%] Running cpp protocol buffer compiler on InterfaceService.proto
[ 13%] Running cpp protocol buffer compiler on InterfaceTraceCreating.proto
[ 14%] Running cpp protocol buffer compiler on InterfaceTraceManagement.proto
InterfaceTraceManagement.proto:8:1: warning: Import defs.proto is unused.
[ 15%] Running cpp protocol buffer compiler on opts.proto
[ 15%] Running cpp protocol buffer compiler on packets.proto
[ 16%] Running cpp protocol buffer compiler on trace.proto
Scanning dependencies of target protooctf
make[3]: Leaving directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
make[3]: Entering directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
[ 17%] Building CXX object modules/open-cas-telemetry-framework/source/octf/proto/CMakeFiles/protooctf.dir/configuration.pb.cc.o
[ 18%] Building CXX object modules/open-cas-telemetry-framework/source/octf/proto/CMakeFiles/protooctf.dir/defs.pb.cc.o
[ 18%] Building CXX object modules/open-cas-telemetry-framework/source/octf/proto/CMakeFiles/protooctf.dir/InterfaceCLI.pb.cc.o
[ 19%] Building CXX object modules/open-cas-telemetry-framework/source/octf/proto/CMakeFiles/protooctf.dir/InterfaceIdentification.pb.cc.o
[ 20%] Building CXX object modules/open-cas-telemetry-framework/source/octf/proto/CMakeFiles/protooctf.dir/InterfaceTraceParsing.pb.cc.o
[ 21%] Building CXX object modules/open-cas-telemetry-framework/source/octf/proto/CMakeFiles/protooctf.dir/InterfaceService.pb.cc.o
[ 21%] Building CXX object modules/open-cas-telemetry-framework/source/octf/proto/CMakeFiles/protooctf.dir/InterfaceTraceCreating.pb.cc.o
[ 22%] Building CXX object modules/open-cas-telemetry-framework/source/octf/proto/CMakeFiles/protooctf.dir/InterfaceTraceManagement.pb.cc.o
[ 23%] Building CXX object modules/open-cas-telemetry-framework/source/octf/proto/CMakeFiles/protooctf.dir/opts.pb.cc.o
[ 24%] Building CXX object modules/open-cas-telemetry-framework/source/octf/proto/CMakeFiles/protooctf.dir/packets.pb.cc.o
[ 25%] Building CXX object modules/open-cas-telemetry-framework/source/octf/proto/CMakeFiles/protooctf.dir/trace.pb.cc.o
[ 25%] Building CXX object modules/open-cas-telemetry-framework/source/octf/proto/CMakeFiles/protooctf.dir/traceDefinitions.pb.cc.o
make[3]: Leaving directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
[ 25%] Built target protooctf
make[3]: Entering directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
Scanning dependencies of target octf
make[3]: Leaving directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
make[3]: Entering directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
[ 26%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/cmd/Command.cpp.o
[ 26%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/cmd/CmdVersion.cpp.o
[ 27%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/cmd/CmdHelp.cpp.o
[ 28%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/cmd/CommandProtobufLocal.cpp.o
[ 29%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/cmd/CommandProtobuf.cpp.o
[ 30%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/param/Parameter.cpp.o
[ 30%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/param/ParamYesNo.cpp.o
[ 31%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/param/ParamHelp.cpp.o
[ 32%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/param/ParamString.cpp.o
[ 33%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/param/ParamEnum.cpp.o
[ 33%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/param/ParamNumber.cpp.o
[ 34%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/CommandSet.cpp.o
[ 35%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/CLIUtils.cpp.o
[ 36%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/CLIElement.cpp.o
[ 37%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/CLIProperties.cpp.o
[ 37%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/GenericPluginShadow.cpp.o
[ 38%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/Module.cpp.o
[ 39%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/CLIList.cpp.o
[ 40%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/cli/Executor.cpp.o
[ 41%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/communication/internal/ConnectionContext.cpp.o
[ 41%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/communication/internal/MethodClient.cpp.o
[ 42%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/communication/internal/ConnectionContextDeleter.cpp.o
[ 43%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/communication/internal/RpcProxy.cpp.o
[ 44%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/communication/Method.cpp.o
[ 44%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/communication/CommunicationManagerClient.cpp.o
[ 45%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/communication/RpcChannelImpl.cpp.o
[ 46%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/communication/RpcControllerImpl.cpp.o
[ 47%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/communication/CommunicationManagerServer.cpp.o
[ 48%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/interface/internal/FileTraceSerializer.cpp.o
/home/seagate/iotracer/standalone-linux-io-tracer/modules/open-cas-telemetry-framework/source/octf/interface/internal/FileTraceSerializer.cpp: In member function ‘virtual bool octf::FileTraceSerializer::serialize(const std::shared_ptr<const google::protobuf::Message>&)’:
/home/seagate/iotracer/standalone-linux-io-tracer/modules/open-cas-telemetry-framework/source/octf/interface/internal/FileTraceSerializer.cpp:97:43: warning: ‘int google::protobuf::MessageLite::ByteSize() const’ is deprecated (declared at /usr/include/google/protobuf/message_lite.h:402): Please use ByteSizeLong() instead [-Wdeprecated-declarations]
     int messageLength = message->ByteSize();
                                           ^
[ 48%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/interface/internal/TraceJob.cpp.o
[ 49%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/interface/InterfaceServiceImpl.cpp.o
[ 50%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/interface/InterfaceTraceManagementImpl.cpp.o
[ 51%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/interface/InterfaceCliImpl.cpp.o
[ 52%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/interface/InterfaceId.cpp.o
[ 52%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/interface/InterfaceTraceParsingImpl.cpp.o
[ 53%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/interface/InterfaceTraceCreatingImpl.cpp.o
[ 54%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/interface/InterfaceIdentificationImpl.cpp.o
[ 55%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/interface/TraceProducerLocal.cpp.o
[ 56%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/interface/TraceManager.cpp.o
[ 56%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/interface/TraceConverter.cpp.o
[ 57%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/node/internal/MethodHandler.cpp.o
[ 58%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/node/internal/ClientEventHandler.cpp.o
[ 59%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/node/internal/NodeShadowEventDispatcher.cpp.o
[ 59%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/node/NodeShadow.cpp.o
[ 60%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/node/NodeClient.cpp.o
[ 61%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/node/NodeId.cpp.o
[ 62%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/node/NodeServer.cpp.o
[ 63%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/node/NodeGeneric.cpp.o
[ 63%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/node/NodeBase.cpp.o
[ 64%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/plugin/internal/ServiceShadow.cpp.o
[ 65%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/plugin/NodePluginShadow.cpp.o
[ 66%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/plugin/NodePlugin.cpp.o
[ 67%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/trace/parser/TraceFileParser.cpp.o
[ 67%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/trace/parser/TraceFileReader.cpp.o
[ 68%] Building C object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/trace/trace.c.o
[ 69%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/socket/internal/unixsocket/Client.cpp.o
[ 70%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/socket/internal/unixsocket/Connection.cpp.o
[ 70%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/socket/internal/unixsocket/Server.cpp.o
[ 71%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/socket/internal/SocketManagerStateMachineServer.cpp.o
[ 72%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/socket/internal/SocketManagerStateMachineClient.cpp.o
[ 73%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/socket/internal/SocketManagerStateMachine.cpp.o
[ 74%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/socket/internal/Packetizer.cpp.o
[ 74%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/socket/SocketFactory.cpp.o
[ 75%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/socket/SocketManager.cpp.o
[ 76%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/socket/ConnectionTransceiver.cpp.o
[ 77%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/socket/SocketConfig.cpp.o
[ 78%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/socket/ISocketConnection.cpp.o
[ 78%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/utils/ModulesDiscover.cpp.o
[ 79%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/utils/OptionsValidation.cpp.o
[ 80%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/utils/ProtobufReaderWriter.cpp.o
[ 81%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/utils/FileOperations.cpp.o
[ 81%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/utils/Log.cpp.o
[ 82%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/utils/Semaphore.cpp.o
[ 83%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/utils/Exception.cpp.o
[ 84%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/utils/FrameworkConfiguration.cpp.o
[ 85%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/utils/SignalHandler.cpp.o
[ 85%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/utils/DateTime.cpp.o
[ 86%] Building CXX object modules/open-cas-telemetry-framework/source/CMakeFiles/octf.dir/octf/utils/ProtoConverter.cpp.o
[ 87%] Linking CXX shared library liboctf.so
make[3]: Leaving directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
[ 87%] Built target octf
make[3]: Entering directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
Scanning dependencies of target octf-tests
make[3]: Leaving directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
make[3]: Entering directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
[ 88%] Building CXX object modules/open-cas-telemetry-framework/tests/CMakeFiles/octf-tests.dir/octf/node/NodeIdTest.cpp.o
[ 89%] Building CXX object modules/open-cas-telemetry-framework/tests/CMakeFiles/octf-tests.dir/octf/socket/unixsocket/ConnectionTest.cpp.o
[ 89%] Building CXX object modules/open-cas-telemetry-framework/tests/CMakeFiles/octf-tests.dir/octf/socket/unixsocket/ServerTest.cpp.o
[ 90%] Building CXX object modules/open-cas-telemetry-framework/tests/CMakeFiles/octf-tests.dir/octf/socket/unixsocket/ClientTest.cpp.o
[ 91%] Building CXX object modules/open-cas-telemetry-framework/tests/CMakeFiles/octf-tests.dir/octf/utils/ProtoConverterTest.cpp.o
[ 92%] Building CXX object modules/open-cas-telemetry-framework/tests/CMakeFiles/octf-tests.dir/octf/trace/TracingTest.cpp.o
[ 93%] Linking CXX executable octf-tests
make[3]: Leaving directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
[ 93%] Built target octf-tests
make[3]: Entering directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
Scanning dependencies of target traceModule
make[3]: Leaving directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
make[3]: Entering directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
[ 94%] Generating ../../../../source/kernel/iotrace.ko
/bin/sh: line 0: cd: /lib/modules/5.3.11-1.el7.elrepo.x86_64/build: No such file or directory
make[3]: *** [../../source/kernel/iotrace.ko] Error 1
make[3]: Leaving directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
make[2]: *** [source/kernel/CMakeFiles/traceModule.dir/all] Error 2
make[2]: Leaving directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/seagate/iotracer/standalone-linux-io-tracer/build/release'
make: *** [all] Error 2

**Comment by mariuszbarczak** [comment]
Hi Apurwa

I see your issue. You are using first release which didn't supported a new kernel. Could you switch to master branch. It should work for you.

BTW, I sow in compilation log that linux headers are missing:  **cd: /lib/modules/5.3.11-1.el7.elrepo.x86_64/build: No such file or directory** Make sure it's available. 

Probably you are using mainline kernel. So the installation would be:
 yum --enablerepo=elrepo-kernel install kernel-ml-devel.

Let me know if it helps,
Regards,
Mariusz.

**Comment by ApurwaMohite** [comment]
Hi,

It started working after switched to master branch. I could install
iotracer successfully on kernel 5.4.1-1.el7.elrepo.x86_64.
Thank you!!

On Wed, Dec 4, 2019 at 8:19 PM Mariusz Barczak <notifications@github.com>
wrote:

> Hi Apurwa
>
> I see your issue. You are using first release which didn't supported a new
> kernel. Could you switch to master branch. It should work for you.
>
> BTW, I sow in compilation log that linux headers are missing: *cd:
> /lib/modules/5.3.11-1.el7.elrepo.x86_64/build: No such file or directory*
> Make sure it's available.
>
> Probably you are using mainline kernel. So the installation would be:
> yum --enablerepo=elrepo-kernel install kernel-ml-devel.
>
> Let me know if it helps,
> Regards,
> Mariusz.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Open-2DCAS_standalone-2Dlinux-2Dio-2Dtracer_issues_107-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DANJ46ENHHRXMKSWFK7LTMRTQW67QBA5CNFSM4JNVXSBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEF5IT6A-23issuecomment-2D561678840&d=DwMCaQ&c=IGDlg0lD0b-nebmJJ0Kp8A&r=NTSMr_hC-2VBlFrr02tMdlG2ZQ7OSSu8BNkih3kl1q0&m=XSjFVRgcoRubymc5hEFO16phfH87HgA1nWWhsXHd9_Q&s=p8li7q3NeRUCc91VxAR2V-DUXGUvFESyIHpwJEJE3RQ&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANJ46EOZ6PJPT4SBMPPGRY3QW67QBANCNFSM4JNVXSBA&d=DwMCaQ&c=IGDlg0lD0b-nebmJJ0Kp8A&r=NTSMr_hC-2VBlFrr02tMdlG2ZQ7OSSu8BNkih3kl1q0&m=XSjFVRgcoRubymc5hEFO16phfH87HgA1nWWhsXHd9_Q&s=IG_8dVNA_sqXYYX7KIGT9Xp0mLom3UjU3Ehv10HaYd8&e=>
> .
>


-- 
Regards,
Apurwa
