### ISSUE TITLE
Memory leaks upon inserting and removing kernel module multiple times.

### ISSUE THREAD

**Issue by tomaszrybicki** [Open-CAS/standalone-linux-io-tracer#139]
During fuzzy tests, iotrace module was inserted (modprobe) and removed(modprobe -r) multiple times (~thousands). After such operation the system hung due to running out of memory, possibly due to kernel allocations,  as no userspace app reported high RAM usage.

**Comment by mariuszbarczak** [comment]
At the moment we run fuzzy tests and reproducing that. And not memory leak. No reproducible any more.
