### ISSUE TITLE
Starting trace fails if iotrace module is loaded before that

### ISSUE THREAD

**Issue by micrakow** [Open-CAS/standalone-linux-io-tracer#150]
Test scenario:
1. Install iotrace
2. modprobe iotrace
3. start tracing (e.g. iotrace -S -d /dev/nvme0n1)

Output after starting and finishing trace:
```
{
 "timestamp": "2020-02-18 00:31.539",
 "system": "iotrace",
 "severity": "Error",
 "trace": "Failed to open trace file: /proc/iotrace//trace_ring.0"
}
^C{
 "timestamp": "2020-02-18 00:31.544",
 "system": "iotrace",
 "severity": "Error",
 "trace": "Tracing not completed, trace path kernel/2020-02-18_00:31:25"
}
```
Without modprobe command starting succeeds properly.

OS: Ubuntu 18.04.3 LTS
kernel: 5.0.0-23-generic

**Comment by mariuszbarczak** [comment]
It was a problem with a test, which uploaded kernel module from host to DUT. Kernels of both machines were different, and on DUT, we weren't able to load kernel module built on test controller OS.
