### ISSUE TITLE
`count` in trace stats is confusing.

### ISSUE THREAD

**Issue by mmichal10** [Open-CAS/standalone-linux-io-tracer#164]
`"write": {
    "size": {
     "unit": "sector",
     "average": "8",
     "min": "8",
     "max": "8",
     **"count": "262144",**
     "total": "2097152",
     "percentiles": {
      "90.000000th": 8.5,
      "99.900000th": 10.5,
      "99.990000th": 11.5,
      "99.000000th": 9.5
     }
    },
    "latency": {
     "unit": "ns",
     "average": "8235",
     "min": "6932",
     "max": "5954144",
     **"count": "262144",**
     "total": "2158819326",
     "percentiles": {
      "99.900000th": 6291456,
      "99.000000th": 24576,
      "90.000000th": 12288
     }
    },
...
}`

`count` field value means number of events. It should be moved out of `latency` and `size` structs.

**Comment by mariuszbarczak** [comment]
A good sight. To be solved.
