### ISSUE TITLE
Wrong permissions for config file and trace dir/files

### ISSUE THREAD

**Issue by Deixx** [Open-CAS/standalone-linux-io-tracer#19]
Config file has proper permissions for root but too broad permissions for group/others (should have none, has read).
For trace dir/files expected permissions are 770/600 respectively.
For default trace dir actual permissions are 755; for all nested dirs and non-default trace path permissions are 760; for trace files 644.

**Comment by mariuszbarczak** [comment]
Comments:
- Config file (/etc/octf/octf.conf) shall be readable for non-root user as well, so expected permission is 644. And actually it's current state
- Regarding to trace files, during creation their permission should be: 600, after stopping tracing expected permission should be: 440
- Main trace directory shall be accessible for all users. And user shall be able to create own traces. So permission should be 777. And it will be set in a next release. Right now 755 is satisfactory. 
- Sub directors shall not be accessible for others, so rights: 750.

**Comment by mariuszbarczak** [comment]
To be fixed:
- Trace files permission 440
- Trace dirs permision 750

**Comment by mariuszbarczak** [comment]
Fixed by #44
