### ISSUE TITLE
Invalid output of iotrace --remove-trace command

### ISSUE THREAD

**Issue by katlapinka** [Open-CAS/standalone-linux-io-tracer#25]
iotrace --remove-trace command should return an empty list - such as, for example, --list-traces command.
Correct output:
{
 "trace": []
}

Actual output:
{}

**Comment by mariuszbarczak** [comment]
Fixed by https://github.com/Open-CAS/open-cas-telemetry-framework/commit/414026aed86ad9fe8920f0043bba0ffa81189d8d
