### ISSUE TITLE
Setting incorrect values in /proc/iotrace/size

### ISSUE THREAD

**Issue by Deixx** [Open-CAS/standalone-linux-io-tracer#28]
I treat writing to the size file as an equivalent of setting --buffer in a start command. Bearing that in mind:
1. You can write values greater than 1024 directly to the file (1024 is max for a start command);
2. After running a start command, the parameter set in the size file is smaller (by 1) than the value used in the start command. With no parameter set (default 100) size file contains 99. I don't know if that is intended, but it is certainly confusing.

**Comment by mariuszbarczak** [comment]
Mismatch is because of division round off. We present actually utilized memory footprint
