### ISSUE TITLE
Parsed results not showing IO Latency values

### ISSUE THREAD

**Issue by jcurryaz60** [Open-CAS/standalone-linux-io-tracer#75]
after collecting data of a mixed FIO run on RAID'd NVMe drives, the parsed output is showing all latency values to be zero. unzip and run iotrace -parse opn these trace files.
[sample.tar.gz](https://github.com/Open-CAS/standalone-linux-io-tracer/files/3513544/sample.tar.gz)

**Comment by tomaszrybicki** [comment]
Probably the same issue as in #98, closing this issue as to not duplicate the issues.
