### ISSUE TITLE
Traces of NVMe admin commands

### ISSUE THREAD

**Issue by ApurwaMohite** [Open-CAS/standalone-linux-io-tracer#88]
Hi,
I am not sure if this is correct place to raise these queries. 
1. I am planning to use standalone-linux-io-tracer for capturing traces of my NVMe drive. I could successfully capture traces when IOs are running on drive. But when admin commands are run no traces are captured. Does this tool captures traces for IOs only? Is there any option to enable the  traces for admin commands? If not, is there any plan to enhance the tool to do so?
2. Is there any option to stop tracing in between? How to stop tracing before the mentioned trace duration?

**Comment by mariuszbarczak** [comment]
Hi,
1. At the moment standalone-linux-io-tracer is not able to trace admin command on a NVMe drive. It could be very interesting information. 
2. To stop tracing just press ctrl+c or send termination signal to the iotrace process

**Comment by ApurwaMohite** [comment]
Hi,

Thanks for your reply.
About the second point. I tried to stop tracing by sending termination
signal (kill -9), tracing stops but the trace file (in which traces are
being captured) remains in Running state (Checked this in 'iotrace
--list'). If I try to parse the trace file which is in running state it
gives error:
[image: image.png]

It won't parse the traces in human readable format.

Is there any other option to achieve this?

On Fri, Sep 27, 2019 at 4:04 PM Mariusz Barczak <notifications@github.com>
wrote:

> Hi,
>
>    1. At the moment standalone-linux-io-tracer is not able to trace admin
>    command on a NVMe drive. It could be very interesting information.
>    2. To stop tracing just press ctrl+c or send termination signal to the
>    iotrace process
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Open-2DCAS_standalone-2Dlinux-2Dio-2Dtracer_issues_88-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DANJ46EPIS4TXQLRHEDTN3U3QLXOUVA5CNFSM4I2VDO62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7YPWSY-23issuecomment-2D535886667&d=DwMCaQ&c=IGDlg0lD0b-nebmJJ0Kp8A&r=NTSMr_hC-2VBlFrr02tMdlG2ZQ7OSSu8BNkih3kl1q0&m=_VgLZAo5eI2iYov0iofE-lnUxGvDhvJzaDJSs6b1Fu4&s=hZdZtJZpl_krM2PgMpGEWXs60JYxwNG0kzNdWtxy15Q&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANJ46EJT27XYSBSDE3Y7JZDQLXOUVANCNFSM4I2VDO6Q&d=DwMCaQ&c=IGDlg0lD0b-nebmJJ0Kp8A&r=NTSMr_hC-2VBlFrr02tMdlG2ZQ7OSSu8BNkih3kl1q0&m=_VgLZAo5eI2iYov0iofE-lnUxGvDhvJzaDJSs6b1Fu4&s=PsFm3B8Zi1pRFUVHs6bC81C6BeYc-hm3hvjgRqUIFA4&e=>
> .
>


-- 
Regards,
Apurwa

**Comment by tomaszrybicki** [comment]
Hi,
To properly stop tracing you need to send the SIGINT signal (2) or SIGTERM(15) instead of SIGKILL signal (9). The SIGKILL signal does not allow the program to properly terminate, hence the traces are in an invalid state.

**Comment by ApurwaMohite** [comment]
Thanks so much! I will try this.

On Mon, Sep 30, 2019 at 4:07 PM Tomasz Rybicki <notifications@github.com>
wrote:

> Hi,
> To properly stop tracing you need to send the SIGINT signal (2) or
> SIGTERM(15) instead of SIGKILL signal (9). The SIGKILL signal does not
> allow the program to properly terminate, hence the traces are in an invalid
> state.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Open-2DCAS_standalone-2Dlinux-2Dio-2Dtracer_issues_88-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DANJ46EMPZS3DJRBFZ6AWGTLQMHJGJA5CNFSM4I2VDO62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD75GU7Q-23issuecomment-2D536504958&d=DwMCaQ&c=IGDlg0lD0b-nebmJJ0Kp8A&r=NTSMr_hC-2VBlFrr02tMdlG2ZQ7OSSu8BNkih3kl1q0&m=0mrukCSRxP9TtOSL7gt0De9wpZRBauKZGZ5LRTNZnZM&s=37ejm0KAqDFzdJry2hPp-WXj8p6QaEqrGyVDmUjPA0A&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANJ46EPSZM574I6XFXYRFSLQMHJGJANCNFSM4I2VDO6Q&d=DwMCaQ&c=IGDlg0lD0b-nebmJJ0Kp8A&r=NTSMr_hC-2VBlFrr02tMdlG2ZQ7OSSu8BNkih3kl1q0&m=0mrukCSRxP9TtOSL7gt0De9wpZRBauKZGZ5LRTNZnZM&s=754jgBLgxpMCkDzQQRMhgcKIFwE_qTArHXQh6t_RILs&e=>
> .
>


-- 
Regards,
Apurwa
