### ISSUE TITLE
Trace data - io.latency and io.qd may not be accurate

### ISSUE THREAD

**Issue by jcurryaz1** [Open-CAS/standalone-linux-io-tracer#93]
I used iotrace and storage snapshot to collect data using a simple FIO script
fio --time_based --name=test --filename=/mnt/data/test --filesize=100G --rw=randrw --rwmixwrite=100 --bssplit=4k --direct=1 --do_verify=0 --eta=never --iodepth=8 --ioengine=libaio --runtime=300 --ramp_time=30 --refill_buffers --numjobs=16 --randrepeat=0 --group_reporting --thread --random_distribution=zipf:1.1 --iodepth_batch_complete_min=8 --iodepth_low=8 --iodepth_batch_submit=8

[iotrace-200lines.xlsx](https://github.com/Open-CAS/standalone-linux-io-tracer/files/3687727/iotrace-200lines.xlsx)

**Comment by tomaszrybicki** [comment]
To be reproduced and fixed soon - functional  tests will be written for this soon.

**Comment by mmkayPL** [comment]
Fixed by #272
